### ISSUE TITLE
Cannot Sign In

### ISSUE THREAD

**Issue by Ednn0nd1au** [4bpb/Chegg-Bot#4]
Hi there,

Thank you for the effort. After trying to sign in, the console gives the feedback:

11:40:48    Initializing   Logged in to Discord as Secret Bot#9146!
11:40:48    Initializing   Browser Deployed
11:40:48    Initializing   No Cookies Sending to Login
/codingProject/Chegg-Bot/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26
        throw new Error(message);
              ^

Error: No node found for selector: #eggshell-2 > form > div > div > div > footer > button
    at Object.assert (/codingProject/Chegg-Bot/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
    at DOMWorld.click (/codingProject/Chegg-Bot/node_modules/puppeteer/lib/cjs/puppeteer/common/DOMWorld.js:277:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async login (/codingProject/Chegg-Bot/index.js:51:5)

**Comment by 4bpb** [comment]
Hello I'll be able to fix that in a couple days on vacation till Thursday!

**Comment by 4bpb** [comment]
Should be fixed now.
